apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pricing-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sejoonkimmm/devops-platform-lab.git
    targetRevision: main
    path: deploy/chart
    helm: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: pricing
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
