apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/sejoonkimmm/devops-platform-lab.git
    targetRevision: main
    path: task-2-deployment/infra
  destination:
    server: https://kubernetes.default.svc
    namespace: pricing
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
